# Derived from nixpkgs' `nixos/modules/services/networking/wg-quick.nix`.
#
# Key differences from the original:
#   - AmneziaWG only (no regular WireGuard kernel module)
#   - No `modprobe` call — the kernel module is never loaded
#   - Sets `WG_QUICK_USERSPACE_IMPLEMENTATION` so `awg-quick` falls
#     back to the userspace daemon (`amneziawg-go`) automatically
#   - Adds `CAP_NET_ADMIN` and `/dev/net/tun` access for the daemon
#
# API is identical to `networking.wg-quick.interfaces` — just replace
# `networking.wg-quick` with `services.amneziawg` in your config.

{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.services.amneziawg;

  # ── Interface options ────────────────────────────────────────────────

  interfaceOpts = { ... }: {
    options = {
      configFile = mkOption {
        example = "/secret/awg0.conf";
        default = null;
        type = with types; nullOr str;
        description = ''
          awg-quick .conf file describing the interface.
          Using this option overrides all other interface configuration.
          See awg-quick manpage for details.
        '';
      };

      address = mkOption {
        example = [ "10.0.0.1/24" ];
        default = [ ];
        type = with types; listOf str;
        description = "IP addresses assigned to the interface.";
      };

      autostart = mkOption {
        description = "Bring up this interface automatically during boot.";
        default = true;
        type = types.bool;
      };

      dns = mkOption {
        example = [ "1.1.1.1" ];
        default = [ ];
        type = with types; listOf str;
        description = "DNS servers pushed to peers via awg-quick.";
      };

      privateKey = mkOption {
        example = "yAnz5TF+lXXJte14tji3zlMNq+hd2rYUIgJBgB3fBmk=";
        type = with types; nullOr str;
        default = null;
        description = ''
          Base64 private key.

          Warning: use privateKeyFile instead if you don't want the
          key stored in the world-readable Nix store.
        '';
      };

      generatePrivateKeyFile = mkOption {
        default = false;
        type = types.bool;
        description = ''
          Automatically generate a private key via `awg genkey`
          at the privateKeyFile location (if the file doesn't exist).
        '';
      };

      privateKeyFile = mkOption {
        example = "/secrets/awg-key";
        type = with types; nullOr str;
        default = null;
        description = ''
          Private key file, as generated by `awg genkey`.
        '';
      };

      listenPort = mkOption {
        default = null;
        type = with types; nullOr int;
        example = 51820;
        description = ''
          16-bit UDP listen port. If null, automatically generated
          from the interface name.
        '';
      };

      preUp = mkOption {
        example = literalExpression ''"''${pkgs.iproute2}/bin/ip netns add foo"'';
        default = "";
        type = with types; coercedTo (listOf str) (concatStringsSep "\n") lines;
        description = "Commands run before interface setup.";
      };

      preDown = mkOption {
        default = "";
        type = with types; coercedTo (listOf str) (concatStringsSep "\n") lines;
        description = "Commands run before interface teardown.";
      };

      postUp = mkOption {
        default = "";
        type = with types; coercedTo (listOf str) (concatStringsSep "\n") lines;
        description = "Commands run after interface setup.";
      };

      postDown = mkOption {
        default = "";
        type = with types; coercedTo (listOf str) (concatStringsSep "\n") lines;
        description = "Commands run after interface teardown.";
      };

      table = mkOption {
        example = "main";
        default = null;
        type = with types; nullOr str;
        description = ''
          Kernel routing table for peer routes. Useful for policy
          routing or VRF. Numeric IDs and names are both accepted.
        '';
      };

      mtu = mkOption {
        example = 1280;
        default = null;
        type = with types; nullOr int;
        description = ''
          Interface MTU. If null, auto-detected from endpoint routes
          (minus 80 bytes for the AmneziaWG header).
        '';
      };

      peers = mkOption {
        default = [ ];
        description = "Peers linked to this interface.";
        type = with types; listOf (submodule peerOpts);
      };

      extraOptions = mkOption {
        type = with types; attrsOf (oneOf [ str int ]);
        default = { };
        example = {
          Jc = 5;
          Jmin = 10;
          Jmax = 42;
          S1 = 60;
          S2 = 90;
        };
        description = ''
          Extra options appended to the [Interface] section of the
          config file. Used for AmneziaWG-specific parameters
          (Jc, Jmin, Jmax, S1, S2, H4–H7).
        '';
      };
    };
  };

  # ── Peer options ─────────────────────────────────────────────────────

  peerOpts = { ... }: {
    options = {
      publicKey = mkOption {
        example = "xTIBA5rboUvnH4htodjb6e697QjLERt1NAB4mZqp8Dg=";
        type = types.str;
        description = "Base64 public key of the peer.";
      };

      presharedKey = mkOption {
        default = null;
        type = with types; nullOr str;
        description = ''
          Base64 preshared key. Optional.

          Warning: use presharedKeyFile instead if you don't want
          the key in the world-readable Nix store.
        '';
      };

      presharedKeyFile = mkOption {
        default = null;
        type = with types; nullOr str;
        description = ''
          File containing the preshared key.
        '';
      };

      allowedIPs = mkOption {
        example = [ "10.0.0.2/32" ];
        type = with types; listOf str;
        description = ''
          IP ranges to route to this peer. The catch-all 0.0.0.0/0
          and ::/0 may be used for routing all traffic.
        '';
      };

      endpoint = mkOption {
        default = null;
        type = with types; nullOr str;
        description = ''
          Peer endpoint as host:port. For a server this is usually
          omitted (peers connect to us).
        '';
      };

      persistentKeepalive = mkOption {
        default = null;
        type = with types; nullOr int;
        example = 25;
        description = ''
          Seconds between keepalive pings (1–65535). Useful for
          keeping NAT mappings alive.
        '';
      };
    };
  };

  # ── Helpers ──────────────────────────────────────────────────────────

  writeScriptFile = name: text: ((pkgs.writeShellScriptBin name text) + "/bin/${name}");

  generatePrivateKeyScript = privateKeyFile: ''
    set -e
    mkdir -p --mode 0755 "${dirOf privateKeyFile}"
    if [ ! -f "${privateKeyFile}" ]; then
      (set -e; umask 077; awg genkey > "${privateKeyFile}")
    fi
  '';

  # ── Systemd unit generator ───────────────────────────────────────────

  generateUnit = name: values:
    assert assertMsg (
      values.configFile != null || ((values.privateKey != null) != (values.privateKeyFile != null))
    ) "Exactly one of privateKey, configFile or privateKeyFile must be set";
    assert assertMsg (
      values.generatePrivateKeyFile == false || values.privateKeyFile != null
    ) "generatePrivateKeyFile requires privateKeyFile to be set";
    let
      generateKeyScriptFile = if values.generatePrivateKeyFile then
        writeScriptFile "generatePrivateKey.sh" (generatePrivateKeyScript values.privateKeyFile)
      else null;

      preUpFile = if values.preUp != "" then writeScriptFile "preUp.sh" values.preUp else null;

      postUp = optional (values.privateKeyFile != null)
        "awg set ${name} private-key <(cat ${values.privateKeyFile})"
        ++ concatMap (peer: optional (peer.presharedKeyFile != null)
          "awg set ${name} peer ${peer.publicKey} preshared-key <(cat ${peer.presharedKeyFile})"
        ) values.peers
        ++ optional (values.postUp != "") values.postUp;
      postUpFile = if postUp != [ ] then
        writeScriptFile "postUp.sh" (concatMapStringsSep "\n" (line: line) postUp)
      else null;

      preDownFile = if values.preDown != "" then writeScriptFile "preDown.sh" values.preDown else null;
      postDownFile = if values.postDown != "" then writeScriptFile "postDown.sh" values.postDown else null;

      # Generate the .conf file that awg-quick expects
      configDir = pkgs.writeTextFile {
        name = "config-${name}";
        executable = false;
        destination = "/${name}.conf";
        text = ''
          [Interface]
          ${concatMapStringsSep "\n" (addr: "Address = ${addr}") values.address}
          ${concatMapStringsSep "\n" (d: "DNS = ${d}") values.dns}
        ''
        + optionalString (values.table != null) "Table = ${values.table}\n"
        + optionalString (values.mtu != null) "MTU = ${toString values.mtu}\n"
        + optionalString (values.privateKey != null) "PrivateKey = ${values.privateKey}\n"
        + optionalString (values.listenPort != null) "ListenPort = ${toString values.listenPort}\n"
        + optionalString (generateKeyScriptFile != null) "PreUp = ${generateKeyScriptFile}\n"
        + optionalString (preUpFile != null) "PreUp = ${preUpFile}\n"
        + optionalString (postUpFile != null) "PostUp = ${postUpFile}\n"
        + optionalString (preDownFile != null) "PreDown = ${preDownFile}\n"
        + optionalString (postDownFile != null) "PostDown = ${postDownFile}\n"
        + concatLines (mapAttrsToList (n: v: "${n} = ${toString v}") values.extraOptions)
        + concatMapStringsSep "\n" (peer:
          assert assertMsg (
            !((peer.presharedKeyFile != null) && (peer.presharedKey != null))
          ) "Only one of presharedKey or presharedKeyFile may be set";
          "[Peer]\n"
          + "PublicKey = ${peer.publicKey}\n"
          + optionalString (peer.presharedKey != null) "PresharedKey = ${peer.presharedKey}\n"
          + optionalString (peer.endpoint != null) "Endpoint = ${peer.endpoint}\n"
          + optionalString (peer.persistentKeepalive != null) "PersistentKeepalive = ${toString peer.persistentKeepalive}\n"
          + optionalString (peer.allowedIPs != [ ]) "AllowedIPs = ${concatStringsSep "," peer.allowedIPs}\n"
        ) values.peers;
      };

      configPath = if values.configFile != null then
        "/tmp/${name}.conf"
      else
        "${configDir}/${name}.conf";
    in
    nameValuePair "wg-quick-${name}" {
      description = "AmneziaWG userspace tunnel - ${name}";
      requires = [ "network-online.target" ];
      after = [ "network.target" "network-online.target" ];
      wantedBy = optional values.autostart "multi-user.target";
      environment.DEVICE = name;

      path = with pkgs; [
        amneziawg-tools
        amneziawg-go
        config.networking.firewall.package
        config.networking.resolvconf.package
      ];

      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        AmbientCapabilities = [ "CAP_NET_ADMIN" ];
        CapabilityBoundingSet = [ "CAP_NET_ADMIN" ];
        DeviceAllow = [ "/dev/net/tun rw" ];
        PrivateTmp = true;
      };

      # No modprobe — awg-quick's add_if() falls back to
      # amneziawg-go automatically when the kernel module is absent.
      # WG_QUICK_USERSPACE_IMPLEMENTATION forces the right binary path.
      script = ''
        ${optionalString (values.configFile != null) ''
          cp ${values.configFile} ${configPath}
        ''}
        export WG_QUICK_USERSPACE_IMPLEMENTATION=${pkgs.amneziawg-go}/bin/amneziawg-go
        awg-quick up ${configPath}
      '';

      preStop = ''
        export WG_QUICK_USERSPACE_IMPLEMENTATION=${pkgs.amneziawg-go}/bin/amneziawg-go
        awg-quick down ${configPath}
      '';
    };

in
{
  meta.maintainers = [ ];

  ###### interface

  options.services.amneziawg = {
    interfaces = mkOption {
      description = ''
        AmneziaWG interfaces running in userspace mode.

        API-identical to `networking.wg-quick.interfaces` — just replace
        `networking.wg-quick` with `services.amneziawg` in your config.

        The key difference: no kernel module is loaded. `awg-quick`
        falls back to `amneziawg-go` (userspace daemon) automatically.
      '';
      default = { };
      example = {
        awg0 = {
          address = [ "10.0.0.1/24" ];
          privateKey = "yAnz5TF+lXXJte14tji3zlMNq+hd2rYUIgJBgB3fBmk=";
          listenPort = 51820;
          extraOptions = { Jc = 5; Jmin = 10; Jmax = 42; S1 = 60; S2 = 90; };
          peers = [
            {
              allowedIPs = [ "10.0.0.2/32" ];
              publicKey = "xTIBA5rboUvnH4htodjb6e697QjLERt1NAB4mZqp8Dg=";
            }
          ];
        };
      };
      type = with types; attrsOf (submodule interfaceOpts);
    };
  };

  ###### implementation

  config = mkIf (cfg.interfaces != { }) {
    environment.systemPackages = with pkgs; [ amneziawg-go amneziawg-tools ];

    systemd.services = mapAttrs' generateUnit cfg.interfaces;

    systemd.network.config.networkConfig.ManageForeignRoutingPolicyRules = mkDefault false;
    systemd.network.wait-online.ignoredInterfaces = builtins.attrNames cfg.interfaces;
  };
}
